backend:
  name: github
  repo: boruto99/vuepress
  branch: master

public_folder: ".vuepress/dist/"
media_folder: ".vuepress/dist/assets/img"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

const Admin = () => import("./Admin");

export default ({ Vue, options, router }) => {
  router.addRoutes([
    {
      path: "/admin",
      component: Admin
    }
  ]);
};
